# Generated by Django 3.2.5 on 2022-05-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0003_alter_record_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='json',
            field=models.JSONField(null=True),
        ),
    ]
