# Generated by Django 3.2.5 on 2022-05-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0005_auto_20220507_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='isloaded',
            field=models.BooleanField(default=False),
        ),
    ]
